### ISSUE TITLE
Не работает. Ошибка вызова методов компоненты

### ISSUE THREAD

**Issue by toyotazaoiat** [bigsoul/3cx_for_1c#1]
ИнформацияОбОшибке | ИнформацияОбОшибке | ИнформацияОбОшибке
-- | -- | --
ИмяМодуля | "Обработка.Телефон.Форма.КоннекторSIP.Форма" | Строка
ИсходнаяСтрока | "   Компонента.НачатьВызовПолучитьВерсиюКомпоненты(ОбратныйВызовSIP);" | Строка
НомерСтроки | 748 | Число
Описание | "Недостаточно фактических параметров" | Строка
Причина |   | Неопределено

**Comment by bigsoul** [comment]
Добрый день, готовится новая версия компоненты, т.к. после обновления АТС на последнюю версию внутренний API изменился. Новая версия ожидается на в течении следующей недели.

**Comment by toyotazaoiat** [comment]
как можно с вами связаться? мой email dborisov@iat.ru

**Comment by bigsoul** [comment]
Протестировано на версии 16.3.0.144, бета тест еще не начался

**Comment by bigsoul** [comment]
Протестировано на win7, win10, примерно на 100 машинах, полет нормальный
